### ISSUE TITLE
Package does not exist

### ISSUE THREAD

**Issue by mhubii** [charliebudd/transferring-relative-monocular-depth-to-surgical-vision#2]
Sorry hope this isn't a local issue. After pip installing I am confronted with: Package `trmdsv` does not exist

```python
>>> import trmdsv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'trmdsv'
```

This error occurs when installing locally

```shell
pip install -e .
```

This error does not occur when installing via url.

**Comment by charliebudd** [comment]
`pip install .` or `python setup.py install` work fine, it seems like editable installs only work if the module is in the same directory as the setup.py file, whereas I have it in a "src" folder, a habit picked up from developing mixed python and c++ packages. Do you need an editable installation?

**Comment by mhubii** [comment]
no that's fine, thank you for the hint
